// Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

// Register Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'


// Logout Constant
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

// Iris Make Prediction Constants
export const PREDICT_REQUEST = 'PREDICT_REQUEST'
export const PREDICT_SUCCESS = 'PREDICT_SUCCESS'
export const PREDICT_FAILED = 'PREDICT_FAILED'